services:
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=PRN222_G5;User Id=sa;Password=P@ssword;TrustServerCertificate=True"
    restart: unless-stopped